#!/usr/bin/env bash
# =============================================================================
# DevShop - generate the Ansible inventory from Terraform outputs.
#
# Reads the control-plane and worker public IPv4s (terraform output) and writes
# ansible/inventory/hosts.ini with the control_plane + workers groups.
# The public IPs change on stop/start (no Elastic IP), so regenerate whenever
# they do (the root ./deploy.sh does this automatically).
#
# The first worker is tagged node_role=app, the rest node_role=monitoring:
# workload scheduling in the Kubernetes manifests keys off these labels.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$ANSIBLE_DIR/.." && pwd)"
TERRAFORM_DIR="$ROOT_DIR/terraform"
INVENTORY_DIR="$ANSIBLE_DIR/inventory"
OUTFILE="$INVENTORY_DIR/hosts.ini"

TERRAFORM_BIN="${TERRAFORM_BIN:-terraform}"

if ! command -v "$TERRAFORM_BIN" >/dev/null 2>&1; then
  echo "ERROR: $TERRAFORM_BIN not found on PATH." >&2
  exit 1
fi
if [ ! -d "$TERRAFORM_DIR" ]; then
  echo "ERROR: terraform directory not found: $TERRAFORM_DIR" >&2
  exit 1
fi

t_output() { "$TERRAFORM_BIN" -chdir="$TERRAFORM_DIR" output -json "$1" 2>/dev/null; }

CP_PUBLIC="$(t_output control_plane_public_ips)"
CP_PRIVATE="$(t_output control_plane_private_ips)"
WORKER_PUBLIC="$(t_output worker_public_ips)"

if [ -z "$CP_PUBLIC" ] || [ "$CP_PUBLIC" = "null" ] || [ -z "$WORKER_PUBLIC" ] || [ "$WORKER_PUBLIC" = "null" ]; then
  echo "ERROR: could not read node outputs. Is the stack applied?" >&2
  exit 1
fi

# Simple JSON string-array parsing (no jq dependency).
parse_list() { python3 -c "import json,sys; print(' '.join(json.load(sys.stdin)))" <<<"$1"; }

mapfile -t CP_PUB_ARR   < <(parse_list "$CP_PUBLIC")
mapfile -t CP_PRIV_ARR  < <(parse_list "$CP_PRIVATE")
mapfile -t WORKER_ARR   < <(parse_list "$WORKER_PUBLIC")

mkdir -p "$INVENTORY_DIR"
{
  echo "# --- Generated by scripts/generate_inventory.sh (do not edit) ---"
  echo "[control_plane]"
  for i in "${!CP_PUB_ARR[@]}"; do
    echo "devshop-cp-${i} ansible_host=${CP_PUB_ARR[$i]} node_role=control-plane"
  done
  echo
  echo "[workers]"
  for i in "${!WORKER_ARR[@]}"; do
    if [ "$i" -eq 0 ]; then
      ROLE="app"
    else
      ROLE="monitoring"
    fi
    # Join endpoint is the control-plane's PRIVATE ip (same subnet).
    echo "devshop-worker-${i} ansible_host=${WORKER_ARR[$i]} ansible_control_plane_private_ip=${CP_PRIV_ARR[0]} node_role=${ROLE}"
  done
  echo
  echo "[all:vars]"
  echo "ansible_user=ubuntu"
} > "$OUTFILE"

echo "Wrote inventory to: $OUTFILE"
echo "  control-plane: ${#CP_PUB_ARR[@]} node(s) / private ${CP_PRIV_ARR[0]}"
echo "  workers: ${#WORKER_ARR[@]} node(s)"