#!/usr/bin/env bash
# =============================================================================
# DevShop — generate Ansible inventory from Terraform outputs.
#
# Writes ansible/inventory/hosts.ini using the EC2 instance's public IPv4
# (terraform output -raw instance_public_ip). The public IP is not hard-coded;
# it changes on stop/start (no Elastic IP), so regenerate when it does.
#
# Usage (from anywhere):
#   DEVSHOP_SSH_KEY=~/.ssh/devshop.pem ./scripts/generate_inventory.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$ANSIBLE_DIR/.." && pwd)"
TERRAFORM_DIR="$ROOT_DIR/terraform"
INVENTORY_DIR="$ANSIBLE_DIR/inventory"
OUTFILE="$INVENTORY_DIR/hosts.ini"

if ! command -v terraform >/dev/null 2>&1; then
  echo "ERROR: terraform not found on PATH." >&2
  exit 1
fi

if [ ! -d "$TERRAFORM_DIR" ]; then
  echo "ERROR: terraform directory not found: $TERRAFORM_DIR" >&2
  exit 1
fi

echo "Reading instance_public_ip from Terraform outputs..."
PUBLIC_IP="$(terraform -chdir="$TERRAFORM_DIR" output -raw instance_public_ip)"

if [ -z "$PUBLIC_IP" ] || [ "$PUBLIC_IP" = "null" ]; then
  echo "ERROR: could not read instance_public_ip. Is the stack applied?" >&2
  exit 1
fi

mkdir -p "$INVENTORY_DIR"
cat > "$OUTFILE" <<EOF
# --- Generated by scripts/generate_inventory.sh ---
# Do not edit by hand.
[devshop]
devshop ansible_host=$PUBLIC_IP
EOF

echo "Wrote inventory to: $OUTFILE"
echo "  Public IPv4: $PUBLIC_IP"
