apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devshop-demo
  labels:
    app: postgres
    app.kubernetes.io/part-of: devshop
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
